const curries = [
  {
    id: "curries",
    title: "Curries",
    items: [
      {
        id: "Punjabi Style Rajma Masala",
        name: "Punjabi Style Rajma Masala",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/01_Punjabi_Style_Rajma_Masala.webp",
      },
      {
        id: "Dal Tadka",
        name: "Dal Tadka",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/02_Dal_Tadka.webp",
      },
      {
        id: "Malai Kofta",
        name: "Malai Kofta",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/03_Malai_Kofta.webp",
      },
      {
        id: "Paneer Pasanda",
        name: "Paneer Pasanda",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/04_Paneer_Pasanda.webp",
      },
      {
        id: "Chana Masala",
        name: "Chana Masala",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/05_Chana_Masala.webp",
      },
      {
        id: "Palak Paneer",
        name: "Palak Paneer",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/06_Palak_Paneer.webp",
      },
      {
        id: "Phool Makhana Corn Palak Curry",
        name: "Phool Makhana Corn Palak Curry",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/07_Phool_Makhana_Corn_Palak_Curry.webp",
      },
      {
        id: "Kaju Paneer",
        name: "Kaju Paneer",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/08_Kaju_Paneer.webp",
      },
      {
        id: "Ananas Menaskai (Pineapple coconut curry)",
        name: "Ananas Menaskai (Pineapple coconut curry)",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/09_Ananas_Menaskai(Pineapple coconut curry).webp",
      },
      {
        id: "Dhaba Style Kaju Tomato Curry",
        name: "Dhaba Style Kaju Tomato Curry",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/10_Dhaba_Style_Kaju_Tomato_Curry.webp",
      },
      {
        id: "Paneer Butter Masala",
        name: "Paneer Butter Masala",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/11_Paneer_Butter_Masala.webp",
      },
      {
        id: "Malai Muttar",
        name: "Malai Muttar",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/12_Malai_Muttar.webp",
      },
      {
        id: "Punjabi Kadhi Pakora",
        name: "Punjabi Kadhi Pakora",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/13_Punjabi_Kadhi_Pakora.jpeg",
      },
      {
        id: "Dal Makhani",
        name: "Dal Makhani",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/14_Dal_Makhani.webp",
      },
      {
        id: "Kadai Paneer",
        name: "Kadai Paneer",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/15_Kadai_Paneer.webp",
      },
      {
        id: "Pindi Chole",
        name: "Pindi Chole",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/16_Pindi_Chole.webp",
      },
      {
        id: "Paneer Do Pyaza",
        name: "Paneer Do Pyaza",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/17_Paneer_Do_Pyaza.webp",
      },
      {
        id: "Mushroom Masala",
        name: "Mushroom Masala",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/18_Mushroom_Masala.webp",
      },
      {
        id: "Matar Paneer Bhurji",
        name: "Matar Paneer Bhurji",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/19_Matar_Paneer_Bhurji.webp",
      },
      {
        id: "Mushroom Hara Pyaz",
        name: "Mushroom Hara Pyaz",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/20_Mushroom_Hara_Pyaz.webp",
      },
      {
        id: "Homestyle Palak Dal Tadka",
        name: "Homestyle Palak Dal Tadka",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/21_Homestyle_Palak_Dal_Tadka.webp",
      },
      {
        id: "Freshly Made Dal Tadka",
        name: "Freshly Made Dal Tadka",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/22_Freshly_Made_Dal_Tadka.webp",
      },
      {
        id: "Veg Kolhapuri",
        name: "Veg Kolhapuri",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/23_Veg_Kolhapuri.jpg",
      },
      {
        id: "Paneer Tikka Masala",
        name: "Paneer Tikka Masala",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/24_Paneer_Tikka_Masala.webp",
      },
      {
        id: "Sambar",
        name: "Sambar",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/25_Sambar.jpg",
      },
      {
        id: "South Indian Dal Curries(Mango, Spinach, etc.,)",
        name: "South Indian Dal Curries(Mango, Spinach, etc.,)",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/26_South_Indian_Dal_Curries(Mango, Spinach, etc.,).jpg",
      },
      {
        id: "Dhondakaya Fry",
        name: "Dhondakaya Fry",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/27_Dhondakaya_Fry.jpg",
      },
      {
        id: "Bendakaya Fry",
        name: "Bendakaya Fry",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/28_Bendakaya_Fry.jpg",
      },
      {
        id: "Cabbage Pakodi",
        name: "Cabbage Pakodi",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/29_Cabbage_Pakodi.jpg",
      },
      {
        id: "Any other fries (aloo bindi, beans fry, etc.,)",
        name: "Any other fries (aloo bindi, beans fry, etc.,)",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/30_Any_other_fries(aloo bindi, beans fry, etc.,).jpg",
      },
      {
        id: "Rasam",
        name: "Rasam",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/31_Rasam.jpg",
      },
      {
        id: "Bombay Sagu",
        name: "Bombay Sagu",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/32_Bombay Sagu.jpg",
      },
      {
        id: "Pulusu Kuralu",
        name: "Pulusu Kuralu",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/03_Curries/33_Pulusu_Kuralu.jpg",
      },
    ],
  },
];

export default curries;
