const appetizers = [
  {
    id: "appetizers",
    title: "Appetizers",
    items: [
      {
        id: "Samosa",
        name: "Samosa",
        price: "$1.00",
        image: "public/images/Appetizers/01_Samosa.webp",
      },
      {
        id: "Vada",
        name: "Vada",
        price: "$1.00",
        image: "public/Bharat-Bhavan-images/01_Appetizers/02_Vada.webp",
      },
      {
        id: "MeduVada",
        name: "Medu vada",
        price: "$1.00",
        image: "public/Bharat-Bhavan-images/01_Appetizers/03_Medu_Vada.webp",
      },
      {
        id: "CurdVada",
        name: "Curd Vada",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/04_Curd_Vada.webp",
      },
      {
        id: "SambarVada",
        name: "Sambar Vada",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/05_Sambar_Vada.webp",
      },
      {
        id: "MasalaVada",
        name: "Masala Vada",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/06_Masala_Vada.webp",
      },
      {
        id: "MysoreBonda",
        name: "Mysore Bonda",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/07_Mysore_Bonda.webp",
      },
      {
        id: "StuffedMirchi",
        name: "Stuffed Mirchi",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/08_Stuffed_Mirchi.webp",
      },
      {
        id: "ChilluGharelu",
        name: "Chillu Gharelu",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/09_Chillu_Gharelu.webp",
      },
      {
        id: "AratikayaBajji",
        name: "Aratikaya Bajji",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/10_Aratikaya_Bajji.jpg",
      },
      {
        id: "AndhraPunugulu",
        name: "Andhra Street Style Punugulu",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/11_Andhra_Street_Style_Punugulu.webp",
      },
      {
        id: "MaddurVade",
        name: "Maddur Vade",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/12_Maddur_Vade.jpeg",
      },
      {
        id: "MixedVegPakoda",
        name: "Mixed Veg. Pakoda",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/13_mixed_veg_pokoda.jpg",
      },
      {
        id: "MangaloreGoliBaje",
        name: "Authentic Mangalore Style Goli Baje with Coconut",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/14_Authentic_Mangalore_Style_Goli_Baje_with_Coconut.webp",
      },
      {
        id: "PunjabiSamosa",
        name: "Punjabi Homemade Samosa",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/15_Punjabi_Homemade_Samosa.webp",
      },
      {
        id: "NormalMirchi",
        name: "Normal Mirchi",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/16_normal_mirchi.webp",
      },
      {
        id: "PaneerCheeseMomos",
        name: "Paneer Cheese Momos",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/17_Paneer_Cheese_Momos.webp",
      },
      {
        id: "MixedVegLollipops",
        name: "Mixed Vegetable Lollipops",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/18_Mixed_Vegetable_Lollipops.webp",
      },
      {
        id: "PaneerCheeseBurst",
        name: "Paneer Cheese Burst",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/19_Paneer_Cheese_Burst.webp",
      },
      {
        id: "StuffedCornCheeseBalls",
        name: "Stuffed Corn Cheese Balls",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/20_Stuffed_Corn_Cheese_Balls.webp",
      },
      {
        id: "CornFitters",
        name: "Corn Fitters",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/21_Corn_Fitters.webp",
      },
      {
        id: "PalakDhaniyaPakoda",
        name: "Palak Dhaniya Pakoda",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/22_Palak_Dhaniya_Pakoda.webp",
      },
      {
        id: "CrispyCorn",
        name: "Home Style Cripsy Corn",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/23_Home_Style_Cripsy_Corn.webp",
      },
      {
        id: "EdamameShikampuriKebab",
        name: "Edamame ki Shikampuri Kebab",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/24_Edamame_ki_Shikampuri_Kebab.webp",
      },
      {
        id: "PaneerGheeRoast",
        name: "Paneer Ghee Roast",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/25_Paneer_Ghee_Roast.webp",
      },
      {
        id: "MushroomGheeRoast",
        name: "Mushroom Ghee Roast",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/26_Mushroom_Ghee_Roast.webp",
      },
      {
        id: "VegManchurian",
        name: "Street Style Veg Manchurian",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/27_street_style_veg_manchurian.jpg",
      },
      {
        id: "ChilliPaneer",
        name: "Pan Fried Chilli Paneer",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/28_pan_fried_chilli_paneer.jpeg",
      },
      {
        id: "LasuniGobi",
        name: "Lasuni Gobi",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/29_lasuni_gobi.webp",
      },
      {
        id: "CurryLeafPaneer",
        name: "Curry Leaf Chilli Paneer",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/30_curry_leaf_chilli_panneer.webp",
      },
      {
        id: "CurryLeafMushroom",
        name: "Spicy Curry Leaf Chilli Mushroom",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/3_spicy_curry_leaf_chilli_mushroom.webp",
      },
      {
        id: "ChilliGobi",
        name: "Chilli Gobi",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/31_Chilli_Gobi.webp",
      },
      {
        id: "DahiCornKebab",
        name: "Dahi Corn Ke Kabab",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/32_Dahi_Corn_Ke_Kabab.webp",
      },
      {
        id: "MushroomPepperFry",
        name: "Mushroom Pepper Fry",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/33_mushroom_pepper_fry.webp",
      },
      {
        id: "DahiKebab",
        name: "Dahi ke Kabab",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/34_dahi_ke_kabab.webp",
      },
      {
        id: "ChapliCornKebab",
        name: "Chapli Corn Kebab",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/35_corn_chapli_kabab.webp",
      },
      {
        id: "BhindiKurkure",
        name: "Bhindi Kurkure",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/36_bhindi_kurkure.webp",
      },
      {
        id: "ChilliBabyCorn",
        name: "Chilli Baby Corn",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/37_chilli_baby_corn.webp",
      },
      {
        id: "VegSoup",
        name: "Vegatable Soup",
        price: "$1.00",
        image: "src/assets/Bharat-Bhavan-images/01_Appetizers/38_vegetable_soup.jpg",
      },
    ],
  },
];

export default appetizers;
